export const sortOptions = [
    {value: 'score_desc', label: 'SCORE DESC.'},
    {value: 'score', label: 'SCORE ASC.'},
    {value: 'title', label: 'TITLE A-Z'},
    {value: 'title_desc', label: 'TITLE Z-A'}
]
export const typeOptions = [
    {value: 'default', label: 'ALL'},
    {value: '0', label: 'TV'},
    {value: '1', label: 'OVA'},
    {value: '2', label: 'MOVIE'},
    {value: '3', label: 'SPECIAL'},
    {value: '4', label: 'ONA'},
]
export const statusOptions = [
    {value: 'default', label: 'ALL'},
    {value: '0', label: 'COMPLETED'},
    {value: '1', label: 'AIRING'},
    {value: '2', label: 'NOT YET AIRED'},
]
export const genreOptions = [
    {value: 'default', label: 'ALL'},
    {value: '57', label: 'Action'},
    {value: '58', label: 'Adventure'},
    {value: '69', label: 'Cars'},
    {value: '59', label: 'Comedy'},
    {value: '84', label: 'Dementia'},
    {value: '86', label: 'Demons'},
    {value: '60', label: 'Drama'},
    {value: '79', label: 'Ecchi'},
    {value: '77', label: 'Fantasy'},
    {value: '93', label: 'Game'},
    {value: '89', label: 'Harem'},
    {value: '82', label: 'Historical'},
    {value: '71', label: 'Horror'},
    {value: '66', label: 'Josei'},
    {value: '95', label: 'Kids'},
    {value: '88', label: 'Magic'},
    {value: '75', label: 'Martial Arts'},
    {value: '85', label: 'Mecha'},
    {value: '83', label: 'Military'},
    {value: '90', label: 'Music'},
    {value: '63', label: 'Mystery'},
    {value: '94', label: 'Parody'},
    {value: '72', label: 'Police'},
    {value: '73', label: 'Psychological'},
    {value: '67', label: 'Romance'},
    {value: '87', label: 'Samurai'},
    {value: '78', label: 'School'},
    {value: '61', label: 'Sci-Fi'},
    {value: '70', label: 'Seinen'},
    {value: '91', label: 'Shoujo'},
    {value: '92', label: 'Shoujo Ai'},
    {value: '64', label: 'Shounen'},
    {value: '96', label: 'Shounen Ai'},
    {value: '68', label: 'Slice of Life'},
    {value: '62', label: 'Space'},
    {value: '65', label: 'Sports'},
    {value: '76', label: 'Super Power'},
    {value: '80', label: 'Supernatural'},
    {value: '74', label: 'Thriller'},
    {value: '81', label: 'Vampire'},
    {value: '98', label: 'Yaoi'},
    {value: '97', label: 'Yuri'}
]